module Products
  class FeatureProductViewModel
    attr_reader name: String
    attr_reader unit_price: BigDecimal

    def initialize: (Product) -> void

    def summary_text: () -> String
  end
end
